Табличку починил
mesenev/lms pull request #96
Opened 2021-08-04 04:50 UTC by TCKACHIKSIS

Нууу , конечно тут все вырвиглазно и топорно в плане кода , но табличка solution list более менее переделана , и визуал можно впринципе поменять , я оставил так , чтобы четко было видно , что все на своем месте.

2021-08-04 04:51 UTC, TCKACHIKSIS commented
запрос на пулрекст

2021-08-11 08:52 UTC, mesenev requested changes

2021-08-11 08:52 UTC, mesenev commented on frontend/src/views/management/SolutionsListView.vue
> +    if (this.submits_request) {
invert this if to reduce nesting

2021-08-11 08:52 UTC, mesenev commented on frontend/src/views/management/SolutionsListView.vue
> +      for (i = 0 ; i < this.submits_request.results.length; i++){
replace for to foreach or map\reduce method call

2021-08-12 06:53 UTC, merged